---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
  takeOwnership: false
spec:
  # note: use valuesContent to overlay custom chart values
  valuesContent: |-
    nodelocal:
      enabled: true
